### ISSUE TITLE
"No such file or directory" when running `mix feedparser.install`

### ISSUE THREAD

**Issue by Mayeu** [draftli/feederer#4]
The feedparser.install mix task assume that mix is run at the level of the feederer mix file. But when feederer is a dependency, the mix task are run from one level up, transforming the [path on this line](https://github.com/draftli/feederer/blob/master/lib/mix/tasks.ex#L10) to `deps/feederer/priv/install.sh`.

Note that I believe it can't be any deeper, since mix seems to store the deps in a flat structure in `deps`.

I'm looking at a clean solution right now, but I did not yet found anything.

**Comment by vhf** [comment]
Thanks!

Solution: in the mix task, check which path exist: (1) `priv/install.sh`, (2) `deps/feederer/priv/install.sh`.
